# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :path => "postgres.sh"
  config.vm.provision :shell, :path => "sentry.sh"

  # PostgreSQL Server port forwarding
  config.vm.forward_port 9000, 9000
end
